/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#176a21",
        "primary-container": "#9df197",
        "primary-dim": "#025d16",
        "secondary": "#3c6600",
        "secondary-container": "#b9f474",
        "secondary-dim": "#345900",
        "tertiary": "#755700",
        "tertiary-container": "#fdc003",
        "tertiary-dim": "#664b00",
        "background": "#f2f9ea",
        "surface": "#f2f9ea",
        "surface-dim": "#ccd8c4",
        "surface-bright": "#f2f9ea",
        "surface-container": "#e2ebda",
        "surface-container-low": "#ebf3e3",
        "surface-container-high": "#dce6d4",
        "surface-container-highest": "#d6e0cd",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d6e0cd",
        "on-surface": "#2a3127",
        "on-surface-variant": "#575e52",
        "on-primary": "#d1ffc8",
        "on-primary-container": "#005c15",
        "on-secondary": "#d9ffab",
        "on-secondary-container": "#365c00",
        "on-tertiary": "#fff1db",
        "on-tertiary-container": "#553e00",
        "outline": "#72796d",
        "outline-variant": "#a8afa2",
        "error": "#b02500",
        "error-container": "#f95630",
      },
      fontFamily: {
        "headline": ["Noto Sans SC", "sans-serif"],
        "body": ["Noto Sans SC", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}
